# Generated by Django 2.2.6 on 2020-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='所属人')),
                ('fund', models.CharField(default='', max_length=100, verbose_name='所属资产')),
                ('sys', models.CharField(choices=[(1, 'IOS'), (2, 'Android')], default='', max_length=100, verbose_name='系统')),
                ('type', models.CharField(default='', max_length=100, verbose_name='型号')),
                ('version', models.CharField(default='', max_length=100, verbose_name='版本')),
                ('creat_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
