# Generated by Django 2.2.6 on 2020-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephone_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tels',
            name='fund',
            field=models.CharField(choices=[(1, 'IOS'), (2, 'Android')], default='', max_length=100, verbose_name='所属资产'),
        ),
    ]
