# Generated by Django 2.2.6 on 2020-10-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephone_manage', '0002_auto_20201005_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tels',
            name='fund',
            field=models.CharField(choices=[(1, '个人'), (2, '公司')], default='', max_length=100, verbose_name='所属资产'),
        ),
    ]
