# Generated by Django 2.2.6 on 2020-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephone_manage', '0003_auto_20201005_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tels',
            name='fund',
            field=models.CharField(choices=[('个人', '个人'), ('公司', '公司')], default='', max_length=100, verbose_name='所属资产'),
        ),
        migrations.AlterField(
            model_name='tels',
            name='sys',
            field=models.CharField(choices=[('IOS', 'IOS'), ('Android', 'Android')], default='', max_length=100, verbose_name='系统'),
        ),
    ]
